export const json = {
  elements: [
    {
      type: "checkbox",
      name: "multiselect",
      title: "choose three adjectives for your mood today",
      isRequired: true,
      colCount: 3,
      itemComponent: "custom-choice-item",
      validators: [
        {
          type: "answercount",
          minCount: 3,
          maxCount: 3,
        },
      ],
      choices: [
        "angry",
        "wonderful",
        "uptight",
        "bored",
        "inert",
        "sad",
        "excited",
        "content",
        "calm",
        "cheerful",
        "mad",
        "fine",
        "anxious",
        "relaxed",
        "defeated",
        "hopeful",
        "worried",
        "depressed",
      ],
      // showOtherItem: true,
      // otherPlaceholder: "enter your mood on your own words here",
      maxSelectedChoices: 3,
    },
    {
      type: "text",
      name: "customOption",
      title: "optional custom feelings",
      requiredErrorText: "Too many characters",
      validators: [
        {
          type: "answercount",
        },
      ],
      maxLength: 50,
    },
  ],
  showQuestionNumbers: false,
};
