name: Unit and Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run prittier
        run: npx prettier --check .
      - name: Run units
        run: npx jest --coverage
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
